package middlewares

var DefaultOptions = map[string]string{
	"BDNCaseProb":                  "0.7",
	"BDNHexValueProb":              "0.7",
	"BDNOIDAttributeMaxSpaces":     "4",
	"BDNOIDAttributeMaxZeros":      "4",
	"BDNOIDAttributeIncludePrefix": "true",

	"FiltSpacingMaxSpaces":            "4",
	"FiltTimestampGarbageMaxChars":    "6",
	"FiltAddBoolMaxDepth":             "4",
	"FiltDblNegBoolMaxDepth":          "1",
	"FiltANRSubstringMaxElems":        "4",
	"FiltSubstringSplitProb":          "0.7",
	"FiltPrependZerosMaxElems":        "4",
	"FiltGarbageMaxElems":             "4",
	"FiltGarbageMaxSize":              "6",
	"FiltGarbageCharset":              "abcdefghijklmnopqrsutwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
	"FiltCaseProb":                    "0.7",
	"FiltHexValueProb":                "0.7",
	"FiltEqExtensibleAppendDN":        "false",
	"FiltBitwiseDecompositionMaxBits": "32",
	"FiltOIDAttributeMaxSpaces":       "4",
	"FiltOIDAttributeMaxZeros":        "4",
	"FiltOIDAttributeIncludePrefix":   "true",

	"AttrsDuplicateProb":              "0.7",
	"AttrsGarbageExistingMaxElems":    "4",
	"AttrsGarbageNonExistingMaxElems": "4",
	"AttrsGarbageNonExistingMaxSize":  "6",
	"AttrsOIDAttributeMaxSpaces":      "4",
	"AttrsOIDAttributeMaxZeros":       "4",
	"AttrsOIDAttributeIncludePrefix":  "true",
}

var DefaultOptionsKeys = []string{
	"BDNCaseProb",
	"BDNHexValueProb",
	"BDNOIDAttributeMaxSpaces",
	"BDNOIDAttributeMaxZeros",
	"BDNOIDAttributeIncludePrefix",

	"FiltSpacingMaxSpaces",
	"FiltTimestampGarbageMaxChars",
	"FiltAddBoolMaxDepth",
	"FiltDblNegBoolMaxDepth",
	"FiltANRSubstringMaxElems",
	"FiltSubstringSplitProb",
	"FiltPrependZerosMaxElems",
	"FiltGarbageMaxElems",
	"FiltGarbageMaxSize",
	"FiltGarbageCharset",
	"FiltOIDAttributeMaxElems",
	"FiltCaseProb",
	"FiltHexValueProb",
	"FiltEqExtensibleAppendDN",
	"FiltBitwiseDecompositionMaxBits",
	"FiltOIDAttributeMaxSpaces",
	"FiltOIDAttributeMaxZeros",
	"FiltOIDAttributeIncludePrefix",

	"AttrsDuplicateProb",
	"AttrsGarbageExistingMaxElems",
	"AttrsGarbageNonExistingMaxElems",
	"AttrsOIDAttributeMaxSpaces",
	"AttrsOIDAttributeMaxZeros",
	"AttrsOIDAttributeIncludePrefix",
}
