package middlewares

var DefaultOptions = map[string]string{
	"BDNCaseProb":                  "0.7",
	"BDNHexValueProb":              "0.7",
	"BDNOIDAttributeMaxSpaces":     "4",
	"BDNOIDAttributeMaxZeros":      "4",
	"BDNOIDAttributeIncludePrefix": "true",
	"BDNSpacingMaxElems":           "4",
	"BDNGuid":                      "",
	"BDNSid":                       "",
	"BDNMatch":                     "",

	"FiltSpacingMaxSpaces":            "4",
	"FiltTimestampGarbageUseComma":    "false",
	"FiltTimestampGarbageMaxChars":    "6",
	"FiltAddBoolMaxDepth":             "4",
	"FiltAddBoolProb":                 "1",
	"FiltDblNegBoolMaxDepth":          "1",
	"FiltDblNegBoolProb":              "1",
	"FiltANRSubstringMaxElems":        "4",
	"FiltSubstringSplitProb":          "0.7",
	"FiltPrependZerosMaxElems":        "4",
	"FiltGarbageMaxElems":             "4",
	"FiltGarbageMaxSize":              "6",
	"FiltGarbageCharset":              "abcdefghijklmnopqrsutwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
	"FiltCaseProb":                    "0.7",
	"FiltHexValueProb":                "0.7",
	"FiltEqExtensibleAppendDN":        "false",
	"FiltBitwiseDecompositionMaxBits": "32",
	"FiltOIDAttributeMaxSpaces":       "4",
	"FiltOIDAttributeMaxZeros":        "4",
	"FiltOIDAttributeIncludePrefix":   "true",
	"FiltDNAttrNoiseProb":             "0.8",
	"FiltObjCategoryRootDN":           "",
	"FiltIgnorableUnicodeProb":        "0.3",
	"FiltIgnorableUnicodeMode":        "all",
	"FiltAltSpaceProb":                "1",

	"AttrsDuplicateProb":              "0.7",
	"AttrsCaseProb":                   "0.7",
	"AttrsGarbageCharset":             "abcdefghijklmnopqrsutwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
	"AttrsGarbageExistingMaxElems":    "4",
	"AttrsGarbageNonExistingMaxElems": "4",
	"AttrsGarbageNonExistingMaxSize":  "6",
	"AttrsOIDAttributeMaxSpaces":      "4",
	"AttrsOIDAttributeMaxZeros":       "4",
	"AttrsOIDAttributeIncludePrefix":  "true",
	"AttrsRangeOption":                "0-*",

	"AttrEntriesCaseProb":                  "0.7",
	"AttrEntriesOIDAttributeMaxSpaces":     "4",
	"AttrEntriesOIDAttributeMaxZeros":      "4",
	"AttrEntriesOIDAttributeIncludePrefix": "true",
}

var DefaultOptionsKeys = []string{
	"BDNCaseProb",
	"BDNHexValueProb",
	"BDNOIDAttributeMaxSpaces",
	"BDNOIDAttributeMaxZeros",
	"BDNOIDAttributeIncludePrefix",
	"BDNSpacingMaxElems",
	"BDNGuid",
	"BDNSid",
	"BDNMatch",

	"FiltSpacingMaxSpaces",
	"FiltTimestampGarbageMaxChars",
	"FiltTimestampGarbageUseComma",
	"FiltAddBoolMaxDepth",
	"FiltAddBoolProb",
	"FiltDblNegBoolMaxDepth",
	"FiltDblNegBoolProb",
	"FiltANRSubstringMaxElems",
	"FiltSubstringSplitProb",
	"FiltPrependZerosMaxElems",
	"FiltGarbageMaxElems",
	"FiltGarbageMaxSize",
	"FiltGarbageCharset",
	"FiltCaseProb",
	"FiltHexValueProb",
	"FiltEqExtensibleAppendDN",
	"FiltBitwiseDecompositionMaxBits",
	"FiltOIDAttributeMaxSpaces",
	"FiltOIDAttributeMaxZeros",
	"FiltOIDAttributeIncludePrefix",
	"FiltDNAttrNoiseProb",
	"FiltObjCategoryRootDN",
	"FiltIgnorableUnicodeProb",
	"FiltIgnorableUnicodeMode",
	"FiltAltSpaceProb",

	"AttrsGarbageExistingMaxElems",
	"AttrsGarbageNonExistingMaxElems",
	"AttrsOIDAttributeMaxSpaces",
	"AttrsOIDAttributeMaxZeros",
	"AttrsOIDAttributeIncludePrefix",
	"AttrsDuplicateProb",
	"AttrsCaseProb",
	"AttrsGarbageCharset",
	"AttrsGarbageNonExistingMaxSize",
	"AttrsRangeOption",

	"AttrEntriesCaseProb",
	"AttrEntriesOIDAttributeMaxSpaces",
	"AttrEntriesOIDAttributeMaxZeros",
	"AttrEntriesOIDAttributeIncludePrefix",
}
